name: Test Suite

on:
  push:
    branches: ['**']
  pull_request:
    branches: [develop, main]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    # Access staging environment secrets for build validation
    environment:
      name: staging
      url: https://dev.autoauthor.app

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      - name: Run unit tests
        run: npm test -- --passWithNoTests --ci --coverage

      - name: Build validation
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: https://api.dev.autoauthor.app/api/v1
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install pytest pytest-cov

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/ --cov=app --cov-report=term-missing --cov-report=xml \
            --ignore=tests/test_debug_chapter_questions.py \
            --ignore=tests/test_debug_questions.py \
            --ignore=tests/test_e2e_no_mocks.py \
            -k "not test_generate_toc_endpoint and not test_toc_generation_workflow_e2e"
        env:
          DATABASE_URI: mongodb://localhost:27017
          DATABASE_NAME: autoauthor_test
          OPENAI_AUTOAUTHOR_API_KEY: test-key-for-ci
          CLERK_API_KEY: test-key-for-ci
          CLERK_JWT_PUBLIC_KEY: test-jwt-public-key-for-ci
          CLERK_FRONTEND_API: https://delicate-ladybird-47.clerk.accounts.dev
          CLERK_BACKEND_API: https://api.clerk.dev
          ENVIRONMENT: test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./backend/coverage.xml
          flags: backend

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'

    # Access staging environment secrets for E2E tests
    environment:
      name: staging
      url: https://dev.autoauthor.app

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npx playwright test
        env:
          NEXT_PUBLIC_API_URL: https://api.dev.autoauthor.app/api/v1
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
